name: 🐛 Bug Report
description: Report unexpected behavior or bugs
title: "[BUG] <short description>"
labels: ["🐛 bug", "🚦 status: pending"]
assignees:
  - ""
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
      placeholder: |
        When I try to X, I expect Y but Z happens instead.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can we see this bug?
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should have happened?
      placeholder: |
        The system should have...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: |
        Instead, it...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Environment, logs, screenshots, etc.
      placeholder: |
        OS: macOS 14.0
        Version: v1.2.3
        Logs: [paste relevant logs]
