name: 🧠 Pre-Implementation Discussion
description: Clarify, analyze, and document technical decisions before any implementation begins.
title: "[DISCUSSION] <short, precise description>"
labels: ["🧠 thinking", "🚦 status: pending"]

body:
  - type: markdown
    attributes:
      value: |
        **Think first. Code second.**

        This discussion exists to slow us down *intentionally* before writing code.
        It helps ensure that:
        - The problem is clearly understood
        - Constraints are explicit
        - Alternatives are considered
        - Decisions are documented for future reference

        Implementation should **not** begin until this discussion is clear and agreed upon.

  - type: textarea
    id: context
    attributes:
      label: Context
      description: What part of the system does this concern? Why does it matter *now*?
      placeholder: |
        Example:
        This concerns the commit workflow in Commando.
        We are about to introduce a new enforcement mechanism and need clarity before implementation.
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem / Uncertainty
      description: What is unclear, risky, undecided, or potentially problematic?
      placeholder: |
        Example:
        It is unclear how strictly commit structure should be enforced
        and whether users should be allowed to partially edit fields.
    validations:
      required: true

  - type: textarea
    id: constraints
    attributes:
      label: Constraints & Assumptions
      description: Rules, non-goals, or assumptions that must hold true.
      placeholder: |
        - Required fields must not be bypassed
        - Tool must work in a Git repository
        - No UI at this stage (text-based only)
        - Domain logic must not depend on UI framework
    validations:
      required: true

  - type: textarea
    id: options
    attributes:
      label: Considered Options
      description: List possible approaches and their trade-offs.
      placeholder: |
        Option A: Prompt all fields sequentially
        - Simple flow
        - Less flexible editing

        Option B: Prompt required fields first, optional later
        - Better UX
        - Slightly more complex control flow
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact Areas
      description: What parts of the system will this decision affect?
      placeholder: |
        - CLI workflow
        - Validation logic
        - Commit message format
        - Testing strategy
        - Future TUI migration
    validations:
      required: false

  - type: textarea
    id: success
    attributes:
      label: Success Criteria
      description: How will we know this decision was correct?
      placeholder: |
        - Commit structure cannot be bypassed
        - Users clearly understand what they are committing
        - Flow feels deliberate, not frustrating
        - Easy to extend without refactoring core logic
    validations:
      required: false

  - type: textarea
    id: decision
    attributes:
      label: Proposed Direction (Optional)
      description: If you have a preferred direction, describe it and explain why.
      placeholder: |
        Preferred approach: Option B
        Reason: Encourages discipline while keeping the workflow flexible.
    validations:
      required: false

  - type: dropdown
    id: status
    attributes:
      label: Decision Status
      description: Current state of this discussion.
      options:
        - Pending discussion
        - Approved for implementation
        - Needs more exploration
        - Rejected
    validations:
      required: true

  - type: textarea
    id: references
    attributes:
      label: References
      description: Related issues, pull requests, documents, or prior art.
      placeholder: |
        - Issue #12: Initial idea discussion
        - docs/architecture/components.md
        - Conventional Commits specification
    validations:
      required: false
